export const AuthTypes = {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    LOGOUT: "LOGOUT",
    UPDATE_USER: "UPDATE_USER",
    GET_OTHER_USER_INFO: "GET_OTHER_USER_INFO",
    CHILDREN_DATA : "CHILDREN_DATA"
}
