export const DriverTypes = {
    GET_DRIVER_RIDE: "GET_DRIVER_RIDE",
    GET_REQUESTED_RIDES: "GET_REQUESTED_RIDES",
    GET_CONFIRMED_RIDES: "GET_CONFIRMED_RIDES",
    GET_PAST_RIDES: "GET_PAST_RIDES",
    GET_LAST_RIDE: "GET_LAST_RIDE",
    GET_RATINGS: "GET_RATINGS",
    GET_MORE_PAST_RIDES: "GET_MORE_PAST_RIDES",
    GET_MORE_CONFIRMED_RIDES: "GET_MORE_CONFIRMED_RIDES",
    GET_MORE_RATINGS: "GET_MORE_RATINGS"
}