export const GeneralTypes = {
    SET_LOADING: "SET_LOADING",
    GET_REVIEWS: "GET_REVIEWS",
    GET_MORE_REVIEWS: "GET_MORE_REVIEWS",
    GET_CONTENT: "GET_CONTENT",
    GET_PAYMENT_CONTENT: "GET_PAYMENT_CONTENT",
    SET_NOTIFY: "SET_NOTIFY",
    GET_RATINGS: "GET_RATINGS",
    GET_MORE_RATINGS: "GET_MORE_RATINGS",

}
