export const PaymentTypes = {
    GET_CARDS: "GET_CARDS",
    DELETE_CARD: "DELETE_CARD",
    UPDATE_CARD: "UPDATE_CARD",
    GET_PAYMENT_HISTORY: "GET_PAYMENT_HISTORY",
    ADD_CARD: "ADD_CARD",
    SELECTED_PAYMENT : "SELECTED_PAYMENT",
}
