export const RideTypes = {
    GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
    GET_MORE_NOTIFICATIONS: "GET_MORE_NOTIFICATIONS",
    RIDE_TYPES: "RIDE_TYPE",
    RIDE_DETAILS : "RIDE_DETAILS",
    SCHEDULE_RIDE : "SCHEDULE_RIDE"
}
