export const SheduleTypes = {
    GET_SHEDULES: "GET_SHEDULES",
    GET_MORE_SHEDULES: "GET_MORE_SHEDULES",
    GET_PAST_RIDES: "GET_PAST_RIDES",
    GET_MORE_PAST_RIDES: "GET_MORE_PAST_RIDES",
    GET_CANCELLED_RIDES: "GET_CANCELLED_RIDES",
    GET_MORE_CANCELLED_RIDES: "GET_MORE_CANCELLED_RIDES",

}
